# set appsec-related template variables
variables:
    WM_APPSEC_GOLANG_IMAGE: "bookworm:20231015"

include:
- local: ".gitlab/pipelines/commit.yml"
  rules:
  - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'push'"
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
- template: Security/Secret-Detection.gitlab-ci.yml
  rules:
  - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'push'"
- template: Security/SAST.gitlab-ci.yml
  rules:
  - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'push'"
- local: ".gitlab/pipelines/weekly.yml"
  rules:
  - if: "$GITLAB_SCHEDULE == 'weekly'"
- local: ".gitlab/pipelines/dependabot.yml"
  rules:
  - if: "$GITLAB_SCHEDULE == 'dependabot'"
- project: 'repos/security/gitlab-ci-security-templates'
  ref: v0.1.6
  file: 'golang-gosec/golang-gosec-ci.yml'