linters:
  disable-all: true
  enable:
    - errcheck # Default
    # - gosimple # Default # Broken with a bunch of errors an 2025
    - govet # Default
    - ineffassign # Default
    # - staticcheck # Default # Broken with a bunch of errors Jan 2025
    - typecheck # Default
    - unused # Default
    # Custom enabled linters
    - bodyclose
    - depguard
    - gci
    - godot
    - gofmt
    - gofumpt
    - goimports
    - importas
    - misspell
    - nolintlint
    - predeclared
    - reassign
    - revive
    - unconvert
    - whitespace
issues:
  exclude-rules:
    - path: \.go
      linters:
        - errcheck
    # Generated code makes a couple of mistakes
    - path: \.gen\.go
      linters:
        - gofumpt
        - goimports

# all available settings of specific linters
linters-settings:
  revive:
    rules:
      # Ignore blank imports, as "embed" is a valid blank import
      - name: blank-imports
        disabled: true
  importas:
    alias:
      - pkg: 	 gitlab.wikimedia.org/repos/releng/cli/internal/util/cobra
        alias: cobrautil
      - pkg: 	 gitlab.wikimedia.org/repos/releng/cli/internal/util/cmd
        alias: cmdutil
      - pkg: 	 gitlab.wikimedia.org/repos/releng/cli/internal/util/ssh
        alias: sshutil
      - pkg: 	 gitlab.wikimedia.org/repos/releng/cli/internal/util/strings
        alias: stringsutil
      - pkg:   gitlab.com/gitlab-org/api/client-go
        alias: gitlab
      - pkg: cgt.name/pkg/go-mwclient
        alias: mwclient
      - pkg: os/exec
        alias: osexec
      - pkg: os/signal
        alias: ossignal
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        list-mode: lax
        deny:
          - pkg: log
            desc: 'logging is allowed only by github.com/sirupsen/logrus'