issues:
  exclude-rules:
    - path: \.go
      linters:
        - errcheck
        - govet

# all available settings of specific linters
linters-settings:
  revive:
    rules:
      # Ignore blank imports, as "embed" is a valid blank import
      - name: blank-imports
        disabled: true
