version: '3.7'

services:
  adminer:
    image: "${ADMINER_IMAGE:-adminer:4}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=adminer.mwdd.localhost,adminer.mwdd
      - VIRTUAL_PORT=8080
      - DEFAULT_EXPOSE_PORT=8080
    depends_on:
      - dps
      - nginx-proxy
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps