
services:
  elasticsearch:
    image: "${ELASTICSEARCH_IMAGE:-docker-registry.wikimedia.org/repos/search-platform/cirrussearch-opensearch-image:v1.3.20-12}"
    security_opt:
      - label:disable
    restart: unless-stopped
    # TODO optionally switch this automatically based on architecture?
    # TODO actually build this image somewhere nicer?
    # on an Apple M1 / arm64 system, you can use kostajh/wmf-elasticsearch-arm64,
    # see https://gitlab.wikimedia.org/kharlan/wmf-elasticsearch-arm64/
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps
    ports:
      - ${ELASTICSEARCH_PORT_9200-}:9200
      - ${ELASTICSEARCH_PORT_9300-}:9300

volumes:
  elasticsearch-data:
    driver: local
