
# https://www.mediawiki.org/wiki/MediaWiki-Docker/Configuration_recipes/EventGate
services:
  eventlogging:
    # https://docker-registry.wikimedia.org/wikimedia/eventgate-wikimedia/tags/
    image: "${EVENTLOGGING_IMAGE:-docker-registry.wikimedia.org/repos/data-engineering/eventgate-wikimedia:v1.26.0}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=eventlogging.local.wmftest.net
      - VIRTUAL_PORT=8192
    entrypoint: /srv/service/node_modules/.bin/eventgate -c config.dev.yaml | /srv/service/node_modules/.bin/bunyan
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps
