version: '3.7'

services:
  mailhog:
    image: "${MAILHOG_IMAGE:-mailhog/mailhog:v1.0.1}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=mailhog.mwdd.localhost,mailhog.mwdd
      - VIRTUAL_PORT=8025
      - DEFAULT_EXPOSE_PORT=8025
    depends_on:
      - nginx-proxy
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps
