version: '3.7'

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=mailhog.mwdd.localhost,mailhog.mwdd
      - VIRTUAL_PORT=8025
    depends_on:
      - nginx-proxy
    dns:
      - 10.0.0.10
    networks:
      - dps
