services:
  novnc:
    image: "${NOVNC_IMAGE:-ghcr.io/montehurd/mediawiki-docker-images/novnc@sha256:57358bd7ab04bf4b39405369cc8e896bb5571251edd97671d8d6227b639bd2e1}"
    restart: unless-stopped
    environment:
      - NOVNC_PORT=8086
      - VIRTUAL_HOST=novnc.mwdd.localhost,novnc.mwdd
      - VIRTUAL_PORT=8086
      - DEFAULT_EXPOSE_PORT=8086
    depends_on:
      - nginx-proxy
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps
