
services:
  postgres: 
    image: "${POSTGRES_IMAGE:-postgres:13.18}"
    security_opt:
      - label:disable
    restart: unless-stopped
    environment:
      # Specify "root" rather than the default "postgres" so that it is similar to the mysql service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - DEFAULT_EXPOSE_PORT=5432
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps
    ports:
      - "${POSTGRES_PORT:-5432}${POSTGRES_PORT:+:5432}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: