
# Images for these services are from the wikimedia image repo
# https://docker-registry.wikimedia.org/wikimedia/mediawiki-libs-shellbox/tags/
# There is one service per image
# TODO can we use the simply named images? or must we use the dated ones to stay up to date?

services:
  shellbox-php-rpc: 
    build: ./shellbox/php-rpc
    restart: unless-stopped
    volumes:
      - shellbox-php-rpc-run:/run/shared
      - ./shellbox/php-rpc/config.json:/srv/app/config/config.json:ro
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps

  shellbox-php-rpc-httpd:
    image: docker-registry.wikimedia.org/httpd-fcgi:latest
    security_opt:
      - label:disable
    volumes:
      - shellbox-php-rpc-run:/run/shared
    environment:
      - "FCGI_MODE=FCGI_UNIX"
      - "SERVERGROUP=main"
      - "APACHE_RUN_PORT=8000"
    depends_on:
      - shellbox-php-rpc
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps

volumes:
  shellbox-php-rpc-run: