version: '3.7'

# Images for these services are from the wikimedia image repo
# https://docker-registry.wikimedia.org/wikimedia/mediawiki-libs-shellbox/tags/
# There is one service per image
# TODO can we use the simply named images? or must we use the dated ones to stay up to date?

services:
  shellbox-timeline: 
    image: "${SHELLBOX_TIMELINE_IMAGE:-docker-registry.wikimedia.org/wikimedia/mediawiki-libs-shellbox:2022-01-06-073153-timeline}"
    dns:
      - 10.0.0.10
    networks:
      - dps
