
# Images for these services are from the wikimedia image repo
# https://docker-registry.wikimedia.org/wikimedia/mediawiki-libs-shellbox/tags/
# There is one service per image
# TODO can we use the simply named images? or must we use the dated ones to stay up to date?

services:
  shellbox-score: 
    image: "${SHELLBOX_SCORE_IMAGE:-docker-registry.wikimedia.org/wikimedia/mediawiki-libs-shellbox:2024-11-18-152217-score81}"
    restart: unless-stopped
    dns:
      - ${NETWORK_SUBNET_PREFIX}.10
    networks:
      - dps