version: '3.7'

services:
  postgres: 
    image: "${POSTGRES_IMAGE:-postgres:13.2}"
    environment:
      # Specify "root" rather than the default "postgres" so that it is similar to the mysql service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    hostname: postgres.mwdd
    dns:
      - 10.0.0.10
    networks:
      - dps
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: