package docker

import (
	_ "embed"
	"os"
	"path/filepath"
	"strings"

	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"gitlab.wikimedia.org/repos/releng/cli/internal/mwdd"
	"gitlab.wikimedia.org/repos/releng/cli/pkg/dockercompose"
)

func NewMwddDestroyCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "destroy",
		GroupID: "core",
		Short:   "Destroy all containers and data",
		RunE: func(cmd *cobra.Command, args []string) error {
			m := mwdd.DefaultForUser()
			err := m.DockerCompose().Down(dockercompose.DownOptions{
				Volumes:       true,
				RemoveOrphans: true,
				Timeout:       1,
			})
			if err != nil {
				return err
			}
			logrus.Debug("Removing used hosts file")
			m.RemoveUsedHostsIfExists()

			if err := cleanupRecipeRuntimeState(m, false); err != nil {
				return err
			}

			mediaWikiPath := m.Env().Get("MEDIAWIKI_VOLUMES_CODE")
			if mediaWikiPath != "" {
				localSettingsDPath := filepath.Clean(filepath.Join(mediaWikiPath, "LocalSettings.d"))
				// Remove recipe-managed files from LocalSettings.d
				// Note: We do NOT delete LocalSettings.php as it may contain user edits
				if err := cleanupRecipeLocalSettingsDFiles(localSettingsDPath); err != nil && !os.IsNotExist(err) {
					return err
				}
			}
			return nil
		},
	}
	cmd.Annotations = make(map[string]string)
	cmd.Annotations["group"] = "Control"
	return cmd
}

// cleanupRecipeLocalSettingsDFiles removes recipe-managed PHP files from LocalSettings.d
// It skips non-existent directories gracefully.
func cleanupRecipeLocalSettingsDFiles(localSettingsDPath string) error {
	entries, err := os.ReadDir(localSettingsDPath)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		// Only delete .php files (recipe-managed files)
		if filepath.Ext(entry.Name()) != ".php" {
			continue
		}

		filePath := filepath.Clean(filepath.Join(localSettingsDPath, entry.Name()))
		contentBytes, err := os.ReadFile(filePath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return err
		}

		// Check if file has recipe management marker
		content := string(contentBytes)
		if !hasRecipeManagementMarker(content) {
			continue
		}

		if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
			return err
		}
		logrus.Debugf("Removed recipe-managed LocalSettings.d file: %s", filePath)
	}

	return nil
}

// hasRecipeManagementMarker checks if a file contains a marker indicating it's recipe-managed
func hasRecipeManagementMarker(content string) bool {
	return strings.Contains(content, "// Generated by mwcli recipe")
}
