package gerrit

import (
	"encoding/json"
	gogerrit "github.com/andygrunwald/go-gerrit"
	cobra "github.com/spf13/cobra"
	output "gitlab.wikimedia.org/repos/releng/cli/internal/util/output"
	"io"
)

// This code is generated by tools/code-gen/main.go. DO NOT EDIT.
func NewGerritAccountsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Accounts Endpoints",
		Use:     "accounts",
	}
	cmd.AddCommand(NewGerritAccountsListCmd())
	cmd.AddCommand(NewGerritAccountsGetCmd())
	cmd.AddCommand(NewGerritAccountsCreateCmd())
	cmd.AddCommand(NewGerritAccountsDeleteCmd())
	cmd.AddCommand(NewGerritAccountsDetailCmd())
	cmd.AddCommand(NewGerritAccountsNameCmd())
	cmd.AddCommand(NewGerritAccountsStatusCmd())
	cmd.AddCommand(NewGerritAccountsUsernameCmd())
	cmd.AddCommand(NewGerritAccountsDisplaynameCmd())
	cmd.AddCommand(NewGerritAccountsActiveCmd())
	cmd.AddCommand(NewGerritAccountsPasswordCmd())
	cmd.AddCommand(NewGerritAccountsOauthtokenCmd())
	cmd.AddCommand(NewGerritAccountsEmailsCmd())
	cmd.AddCommand(NewGerritAccountsSshkeysCmd())
	cmd.AddCommand(NewGerritAccountsGpgkeysCmd())
	cmd.AddCommand(NewGerritAccountsCapabilitiesCmd())
	cmd.AddCommand(NewGerritAccountsGroupsCmd())
	cmd.AddCommand(NewGerritAccountsAvatarCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesCmd())
	cmd.AddCommand(NewGerritAccountsWatchedCmd())
	cmd.AddCommand(NewGerritAccountsExternalCmd())
	cmd.AddCommand(NewGerritAccountsAgreementsCmd())
	cmd.AddCommand(NewGerritAccountsDraftsCmd())
	cmd.AddCommand(NewGerritAccountsIndexCmd())
	cmd.AddCommand(NewGerritAccountsStarredCmd())
	return cmd
}
func NewGerritAccountsListCmd() *cobra.Command {
	type flags struct {
		query string
		limit string
		start string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/"
			path = addParamToPath(path, "q", cmdFlags.query)
			path = addParamToPath(path, "n", cmdFlags.limit)
			path = addParamToPath(path, "S", cmdFlags.start)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Query Account",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.query, "query", "", "Query string to find accounts.")
	cmd.Flags().StringVar(&cmdFlags.limit, "limit", "", "Maximum number of accounts to return.")
	cmd.Flags().StringVar(&cmdFlags.start, "start", "", "Number of accounts to skip.")
	return cmd
}
func NewGerritAccountsGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsCreateCmd() *cobra.Command {
	type flags struct {
		username string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{username}/"
			path = addParamToPath(path, "username", cmdFlags.username)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Account",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.username, "username", "", "The username to operate on.")
	cmd.MarkFlagRequired("username")
	return cmd
}
func NewGerritAccountsDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Account",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsDetailCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/detail/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account Details",
		Use:   "detail",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsNameCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Name",
		Use:     "name",
	}
	cmd.AddCommand(NewGerritAccountsNameGetCmd())
	cmd.AddCommand(NewGerritAccountsNameSetCmd())
	cmd.AddCommand(NewGerritAccountsNameDeleteCmd())
	return cmd
}
func NewGerritAccountsNameGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/name/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account Name",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsNameSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/name/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Account Name",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsNameDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/name/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Account Name",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsStatusCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Status",
		Use:     "status",
	}
	cmd.AddCommand(NewGerritAccountsStatusGetCmd())
	cmd.AddCommand(NewGerritAccountsStatusSetCmd())
	return cmd
}
func NewGerritAccountsStatusGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/status/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account Status",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsStatusSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/status/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Account Status",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsUsernameCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Username",
		Use:     "username",
	}
	cmd.AddCommand(NewGerritAccountsUsernameGetCmd())
	cmd.AddCommand(NewGerritAccountsUsernameSetCmd())
	return cmd
}
func NewGerritAccountsUsernameGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/username/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Username",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsUsernameSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/username/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Username",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsDisplaynameCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/displayname/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Display Name",
		Use:   "displayname",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsActiveCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Active",
		Use:     "active",
	}
	cmd.AddCommand(NewGerritAccountsActiveGetCmd())
	cmd.AddCommand(NewGerritAccountsActiveSetCmd())
	cmd.AddCommand(NewGerritAccountsActiveDeleteCmd())
	return cmd
}
func NewGerritAccountsActiveGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/active/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Active",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsActiveSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/active/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Active",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsActiveDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/active/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Active",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPasswordCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Password",
		Use:     "password",
	}
	cmd.AddCommand(NewGerritAccountsPasswordHttpCmd())
	return cmd
}
func NewGerritAccountsPasswordHttpCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Http",
		Use:     "http",
	}
	cmd.AddCommand(NewGerritAccountsPasswordHttpGenerateCmd())
	cmd.AddCommand(NewGerritAccountsPasswordHttpDeleteCmd())
	return cmd
}
func NewGerritAccountsPasswordHttpGenerateCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/password.http/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			var reqBody interface{}
			err := json.Unmarshal([]byte("{\"generate\": true}"), &reqBody)
			if err != nil {
				return err
			}

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, reqBody, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set/Generate HTTP Password",
		Use:   "generate",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPasswordHttpDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/password.http/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete HTTP Password",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsOauthtokenCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/oauthtoken/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get OAuth Access Token",
		Use:   "oauthtoken",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsEmailsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Emails",
		Use:     "emails",
	}
	cmd.AddCommand(NewGerritAccountsEmailsListCmd())
	cmd.AddCommand(NewGerritAccountsEmailsGetCmd())
	cmd.AddCommand(NewGerritAccountsEmailsCreateCmd())
	cmd.AddCommand(NewGerritAccountsEmailsDeleteCmd())
	cmd.AddCommand(NewGerritAccountsEmailsPreferredCmd())
	return cmd
}
func NewGerritAccountsEmailsListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/emails/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Account Emails",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsEmailsGetCmd() *cobra.Command {
	type flags struct {
		account string
		email   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/emails/{email-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "email-id", cmdFlags.email)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account Email",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.email, "email", "", "The email to operate on.")
	cmd.MarkFlagRequired("email")
	return cmd
}
func NewGerritAccountsEmailsCreateCmd() *cobra.Command {
	type flags struct {
		account string
		email   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/emails/{email-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "email-id", cmdFlags.email)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Account Email",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.email, "email", "", "The email to operate on.")
	cmd.MarkFlagRequired("email")
	return cmd
}
func NewGerritAccountsEmailsDeleteCmd() *cobra.Command {
	type flags struct {
		account string
		email   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/emails/{email-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "email-id", cmdFlags.email)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Account Email",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.email, "email", "", "The email to operate on.")
	cmd.MarkFlagRequired("email")
	return cmd
}
func NewGerritAccountsEmailsPreferredCmd() *cobra.Command {
	type flags struct {
		account string
		email   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/emails/{email-id}/preferred/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "email-id", cmdFlags.email)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Preferred Email",
		Use:   "preferred",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.email, "email", "", "The email to operate on.")
	cmd.MarkFlagRequired("email")
	return cmd
}
func NewGerritAccountsSshkeysCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Sshkeys",
		Use:     "sshkeys",
	}
	cmd.AddCommand(NewGerritAccountsSshkeysListCmd())
	cmd.AddCommand(NewGerritAccountsSshkeysGetCmd())
	cmd.AddCommand(NewGerritAccountsSshkeysDeleteCmd())
	return cmd
}
func NewGerritAccountsSshkeysListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/sshkeys/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List SSH Keys",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsSshkeysGetCmd() *cobra.Command {
	type flags struct {
		account string
		sshkey  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/sshkeys/{ssh-key-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "ssh-key-id", cmdFlags.sshkey)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get SSH Key",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.sshkey, "sshkey", "", "The sshkey to operate on.")
	cmd.MarkFlagRequired("sshkey")
	return cmd
}
func NewGerritAccountsSshkeysDeleteCmd() *cobra.Command {
	type flags struct {
		account string
		sshkey  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/sshkeys/{ssh-key-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "ssh-key-id", cmdFlags.sshkey)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete SSH Key",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.sshkey, "sshkey", "", "The sshkey to operate on.")
	cmd.MarkFlagRequired("sshkey")
	return cmd
}
func NewGerritAccountsGpgkeysCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Gpgkeys",
		Use:     "gpgkeys",
	}
	cmd.AddCommand(NewGerritAccountsGpgkeysListCmd())
	cmd.AddCommand(NewGerritAccountsGpgkeysGetCmd())
	cmd.AddCommand(NewGerritAccountsGpgkeysPostCmd())
	cmd.AddCommand(NewGerritAccountsGpgkeysDeleteCmd())
	return cmd
}
func NewGerritAccountsGpgkeysListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/gpgkeys/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List GPG Keys",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsGpgkeysGetCmd() *cobra.Command {
	type flags struct {
		account string
		gpgkey  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/gpgkeys/{gpg-key-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "gpg-key-id", cmdFlags.gpgkey)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get GPG Key",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.gpgkey, "gpgkey", "", "The gpgkey to operate on.")
	cmd.MarkFlagRequired("gpgkey")
	return cmd
}
func NewGerritAccountsGpgkeysPostCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/gpgkeys/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add/Delete GPG Keys",
		Use:   "post",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsGpgkeysDeleteCmd() *cobra.Command {
	type flags struct {
		account string
		gpgkey  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/gpgkeys/{gpg-key-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "gpg-key-id", cmdFlags.gpgkey)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete GPG Key",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.gpgkey, "gpgkey", "", "The gpgkey to operate on.")
	cmd.MarkFlagRequired("gpgkey")
	return cmd
}
func NewGerritAccountsCapabilitiesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Capabilities",
		Use:     "capabilities",
	}
	cmd.AddCommand(NewGerritAccountsCapabilitiesListCmd())
	cmd.AddCommand(NewGerritAccountsCapabilitiesCheckCmd())
	return cmd
}
func NewGerritAccountsCapabilitiesListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/capabilities/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Account Capabilities",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsCapabilitiesCheckCmd() *cobra.Command {
	type flags struct {
		account    string
		capability string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/capabilities/{capability-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "capability-id", cmdFlags.capability)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Check Account Capability",
		Use:   "check",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.capability, "capability", "", "The capability to operate on.")
	cmd.MarkFlagRequired("capability")
	return cmd
}
func NewGerritAccountsGroupsCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/groups/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Groups",
		Use:   "groups",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsAvatarCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Avatar",
		Use:     "avatar",
	}
	cmd.AddCommand(NewGerritAccountsAvatarGetCmd())
	cmd.AddCommand(NewGerritAccountsAvatarChangeCmd())
	return cmd
}
func NewGerritAccountsAvatarGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/avatar/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Avatar",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsAvatarChangeCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/avatar.change.url/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Avatar Change URL",
		Use:   "change",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Preferences",
		Use:     "preferences",
	}
	cmd.AddCommand(NewGerritAccountsPreferencesGetCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesSetCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesDiffCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesEditCmd())
	return cmd
}
func NewGerritAccountsPreferencesGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get User Preferences",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set User Preferences",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesDiffCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Diff",
		Use:     "diff",
	}
	cmd.AddCommand(NewGerritAccountsPreferencesDiffGetCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesDiffSetCmd())
	return cmd
}
func NewGerritAccountsPreferencesDiffGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences.diff/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Diff Preferences",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesDiffSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences.diff/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Diff Preferences",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesEditCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Edit",
		Use:     "edit",
	}
	cmd.AddCommand(NewGerritAccountsPreferencesEditGetCmd())
	cmd.AddCommand(NewGerritAccountsPreferencesEditSetCmd())
	return cmd
}
func NewGerritAccountsPreferencesEditGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences.edit/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Edit Preferences",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsPreferencesEditSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/preferences.edit/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Edit Preferences",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsWatchedCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Watched",
		Use:     "watched",
	}
	cmd.AddCommand(NewGerritAccountsWatchedProjectsCmd())
	return cmd
}
func NewGerritAccountsWatchedProjectsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Projects",
		Use:     "projects",
	}
	cmd.AddCommand(NewGerritAccountsWatchedProjectsGetCmd())
	cmd.AddCommand(NewGerritAccountsWatchedProjectsSetCmd())
	cmd.AddCommand(NewGerritAccountsWatchedProjectsDeleteCmd())
	return cmd
}
func NewGerritAccountsWatchedProjectsGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/watched.projects/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Watched Projects",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsWatchedProjectsSetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/watched.projects/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add/Update a List of Watched Project Entities",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsWatchedProjectsDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/watched.projects:delete/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Watched Projects",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsExternalCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "External",
		Use:     "external",
	}
	cmd.AddCommand(NewGerritAccountsExternalIdsCmd())
	return cmd
}
func NewGerritAccountsExternalIdsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Ids",
		Use:     "ids",
	}
	cmd.AddCommand(NewGerritAccountsExternalIdsGetCmd())
	cmd.AddCommand(NewGerritAccountsExternalIdsDeleteCmd())
	return cmd
}
func NewGerritAccountsExternalIdsGetCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/external.ids/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Account External IDs",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsExternalIdsDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/external.ids:delete/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Account External IDs",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsAgreementsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Agreements",
		Use:     "agreements",
	}
	cmd.AddCommand(NewGerritAccountsAgreementsListCmd())
	cmd.AddCommand(NewGerritAccountsAgreementsSignCmd())
	return cmd
}
func NewGerritAccountsAgreementsListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/agreements/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Contributor Agreements",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsAgreementsSignCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/agreements/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Sign Contributor Agreement",
		Use:   "sign",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsDraftsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Drafts",
		Use:     "drafts",
	}
	cmd.AddCommand(NewGerritAccountsDraftsDeleteCmd())
	return cmd
}
func NewGerritAccountsDraftsDeleteCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/drafts:delete/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Draft Comments",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsIndexCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/index/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Index Account",
		Use:   "index",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsStarredCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Starred",
		Use:     "starred",
	}
	cmd.AddCommand(NewGerritAccountsStarredChangesCmd())
	return cmd
}
func NewGerritAccountsStarredChangesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Changes",
		Use:     "changes",
	}
	cmd.AddCommand(NewGerritAccountsStarredChangesListCmd())
	cmd.AddCommand(NewGerritAccountsStarredChangesStarCmd())
	cmd.AddCommand(NewGerritAccountsStarredChangesUnstarCmd())
	return cmd
}
func NewGerritAccountsStarredChangesListCmd() *cobra.Command {
	type flags struct {
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/starred.changes/"
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Changes With Default Star",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritAccountsStarredChangesStarCmd() *cobra.Command {
	type flags struct {
		account string
		change  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/starred.changes/{change-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "change-id", cmdFlags.change)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Put Default Star On Change",
		Use:   "star",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.change, "change", "", "The change to operate on.")
	cmd.MarkFlagRequired("change")
	return cmd
}
func NewGerritAccountsStarredChangesUnstarCmd() *cobra.Command {
	type flags struct {
		account string
		change  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/accounts/{account-id}/starred.changes/{change-id}/"
			path = addParamToPath(path, "account-id", cmdFlags.account)
			path = addParamToPath(path, "change-id", cmdFlags.change)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Remove Default Star From Change",
		Use:   "unstar",
	}
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	cmd.Flags().StringVar(&cmdFlags.change, "change", "", "The change to operate on.")
	cmd.MarkFlagRequired("change")
	return cmd
}
