package gerrit

import (
	gogerrit "github.com/andygrunwald/go-gerrit"
	cobra "github.com/spf13/cobra"
	output "gitlab.wikimedia.org/repos/releng/cli/internal/util/output"
	"io"
)

// This code is generated by tools/code-gen/main.go. DO NOT EDIT.
func NewGerritGroupsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Group Endpoints",
		Use:     "groups",
	}
	cmd.AddCommand(NewGerritGroupsListCmd())
	cmd.AddCommand(NewGerritGroupsGetCmd())
	cmd.AddCommand(NewGerritGroupsCreateCmd())
	cmd.AddCommand(NewGerritGroupsDetailCmd())
	cmd.AddCommand(NewGerritGroupsNameCmd())
	cmd.AddCommand(NewGerritGroupsDescriptionCmd())
	cmd.AddCommand(NewGerritGroupsOptionsCmd())
	cmd.AddCommand(NewGerritGroupsOwnerCmd())
	cmd.AddCommand(NewGerritGroupsLogCmd())
	cmd.AddCommand(NewGerritGroupsIndexCmd())
	cmd.AddCommand(NewGerritGroupsMembersCmd())
	cmd.AddCommand(NewGerritGroupsGroupsCmd())
	return cmd
}
func NewGerritGroupsListCmd() *cobra.Command {
	type flags struct {
		query string
		limit string
		start string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/"
			path = addParamToPath(path, "q", cmdFlags.query)
			path = addParamToPath(path, "n", cmdFlags.limit)
			path = addParamToPath(path, "S", cmdFlags.start)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Groups",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.query, "query", "", "Query string to find groups.")
	cmd.Flags().StringVar(&cmdFlags.limit, "limit", "", "Maximum number of groups to return.")
	cmd.Flags().StringVar(&cmdFlags.start, "start", "", "Number of groups to skip.")
	return cmd
}
func NewGerritGroupsGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsCreateCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-name}/"
			path = addParamToPath(path, "group-name", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Group",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsDetailCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/detail/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Detail",
		Use:   "detail",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsNameCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Name",
		Use:     "name",
	}
	cmd.AddCommand(NewGerritGroupsNameGetCmd())
	cmd.AddCommand(NewGerritGroupsNameSetCmd())
	return cmd
}
func NewGerritGroupsNameGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/name/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Name",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsNameSetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/name/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Rename Group",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsDescriptionCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Description",
		Use:     "description",
	}
	cmd.AddCommand(NewGerritGroupsDescriptionGetCmd())
	cmd.AddCommand(NewGerritGroupsDescriptionSetCmd())
	cmd.AddCommand(NewGerritGroupsDescriptionDeleteCmd())
	return cmd
}
func NewGerritGroupsDescriptionGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/description/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Description",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsDescriptionSetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/description/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Group Description",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsDescriptionDeleteCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/description/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Group Description",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsOptionsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Options",
		Use:     "options",
	}
	cmd.AddCommand(NewGerritGroupsOptionsGetCmd())
	cmd.AddCommand(NewGerritGroupsOptionsSetCmd())
	return cmd
}
func NewGerritGroupsOptionsGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/options/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Options",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsOptionsSetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/options/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Group Options",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsOwnerCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Owner",
		Use:     "owner",
	}
	cmd.AddCommand(NewGerritGroupsOwnerGetCmd())
	cmd.AddCommand(NewGerritGroupsOwnerSetCmd())
	return cmd
}
func NewGerritGroupsOwnerGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/owner/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Owner",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsOwnerSetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/owner/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Group Owner",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsLogCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Log",
		Use:     "log",
	}
	cmd.AddCommand(NewGerritGroupsLogAuditCmd())
	return cmd
}
func NewGerritGroupsLogAuditCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/log.audit/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Audit Log",
		Use:   "audit",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsIndexCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/index/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Index Group",
		Use:   "index",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsMembersCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Members",
		Use:     "members",
	}
	cmd.AddCommand(NewGerritGroupsMembersListCmd())
	cmd.AddCommand(NewGerritGroupsMembersGetCmd())
	cmd.AddCommand(NewGerritGroupsMembersAddCmd())
	cmd.AddCommand(NewGerritGroupsMembersAdd2Cmd())
	cmd.AddCommand(NewGerritGroupsMembersDeleteCmd())
	return cmd
}
func NewGerritGroupsMembersListCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/members/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Group Members",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsMembersGetCmd() *cobra.Command {
	type flags struct {
		group   string
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/members/{account-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Group Member",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritGroupsMembersAddCmd() *cobra.Command {
	type flags struct {
		group   string
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/members/{account-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add Group Member",
		Use:   "add",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritGroupsMembersAdd2Cmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/members/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add Group Members",
		Use:   "add-2",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsMembersDeleteCmd() *cobra.Command {
	type flags struct {
		group   string
		account string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/members/{account-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)
			path = addParamToPath(path, "account-id", cmdFlags.account)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Remove Group Member",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	cmd.Flags().StringVar(&cmdFlags.account, "account", "self", "The account identifier.")
	return cmd
}
func NewGerritGroupsGroupsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Groups",
		Use:     "groups",
	}
	cmd.AddCommand(NewGerritGroupsGroupsListCmd())
	cmd.AddCommand(NewGerritGroupsGroupsGetCmd())
	cmd.AddCommand(NewGerritGroupsGroupsAddCmd())
	cmd.AddCommand(NewGerritGroupsGroupsAdd2Cmd())
	cmd.AddCommand(NewGerritGroupsGroupsDeleteCmd())
	return cmd
}
func NewGerritGroupsGroupsListCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/groups/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Subgroups",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsGroupsGetCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/groups/{group-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Subgroup",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsGroupsAddCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/groups/{group-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add Subgroup",
		Use:   "add",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsGroupsAdd2Cmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/groups/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add Subgroups",
		Use:   "add-2",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
func NewGerritGroupsGroupsDeleteCmd() *cobra.Command {
	type flags struct {
		group string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/groups/{group-id}/groups/{group-id}/"
			path = addParamToPath(path, "group-id", cmdFlags.group)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Remove Subgroup",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.group, "group", "", "The group to operate on.")
	cmd.MarkFlagRequired("group")
	return cmd
}
