package gerrit

import (
	gogerrit "github.com/andygrunwald/go-gerrit"
	cobra "github.com/spf13/cobra"
	output "gitlab.wikimedia.org/repos/releng/cli/internal/util/output"
	"io"
)

// This code is generated by tools/code-gen/main.go. DO NOT EDIT.
func NewGerritProjectsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Project Endpoints",
		Use:     "projects",
	}
	cmd.AddCommand(NewGerritProjectsListCmd())
	cmd.AddCommand(NewGerritProjectsGetCmd())
	cmd.AddCommand(NewGerritProjectsCreateCmd())
	cmd.AddCommand(NewGerritProjectsDescriptionCmd())
	cmd.AddCommand(NewGerritProjectsParentCmd())
	cmd.AddCommand(NewGerritProjectsHEADCmd())
	cmd.AddCommand(NewGerritProjectsStatisticsCmd())
	cmd.AddCommand(NewGerritProjectsConfigCmd())
	cmd.AddCommand(NewGerritProjectsGcCmd())
	cmd.AddCommand(NewGerritProjectsBanCmd())
	cmd.AddCommand(NewGerritProjectsAccessCmd())
	cmd.AddCommand(NewGerritProjectsMyProjectCmd())
	cmd.AddCommand(NewGerritProjectsBranchesCmd())
	cmd.AddCommand(NewGerritProjectsChangesCmd())
	cmd.AddCommand(NewGerritProjectsChildrenCmd())
	cmd.AddCommand(NewGerritProjectsTagsCmd())
	cmd.AddCommand(NewGerritProjectsCommitsCmd())
	cmd.AddCommand(NewGerritProjectsDashboardsCmd())
	cmd.AddCommand(NewGerritProjectsLabelsCmd())
	cmd.AddCommand(NewGerritProjectsSubmitRequirementsCmd())
	return cmd
}
func NewGerritProjectsListCmd() *cobra.Command {
	type flags struct {
		query string
		limit string
		start string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/"
			path = addParamToPath(path, "q", cmdFlags.query)
			path = addParamToPath(path, "n", cmdFlags.limit)
			path = addParamToPath(path, "S", cmdFlags.start)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Projects",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.query, "query", "", "Query string to find projects.")
	cmd.Flags().StringVar(&cmdFlags.limit, "limit", "", "Maximum number of projects to return.")
	cmd.Flags().StringVar(&cmdFlags.start, "start", "", "Number of projects to skip.")
	return cmd
}
func NewGerritProjectsGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Project",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsCreateCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Project",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsDescriptionCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Description",
		Use:     "description",
	}
	cmd.AddCommand(NewGerritProjectsDescriptionGetCmd())
	cmd.AddCommand(NewGerritProjectsDescriptionSetCmd())
	cmd.AddCommand(NewGerritProjectsDescriptionDeleteCmd())
	return cmd
}
func NewGerritProjectsDescriptionGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/description/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Project Description",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsDescriptionSetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/description/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Project Description",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsDescriptionDeleteCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/description/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Project Description",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsParentCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Parent",
		Use:     "parent",
	}
	cmd.AddCommand(NewGerritProjectsParentGetCmd())
	cmd.AddCommand(NewGerritProjectsParentSetCmd())
	return cmd
}
func NewGerritProjectsParentGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/parent/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Project Parent",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsParentSetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/parent/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Project Parent",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsHEADCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "HEAD",
		Use:     "HEAD",
	}
	cmd.AddCommand(NewGerritProjectsHEADGetCmd())
	cmd.AddCommand(NewGerritProjectsHEADSetCmd())
	return cmd
}
func NewGerritProjectsHEADGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/HEAD/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get HEAD",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsHEADSetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/HEAD/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set HEAD",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsStatisticsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Statistics",
		Use:     "statistics",
	}
	cmd.AddCommand(NewGerritProjectsStatisticsGitCmd())
	return cmd
}
func NewGerritProjectsStatisticsGitCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/statistics.git/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Repository Statistics",
		Use:   "git",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsConfigCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Config",
		Use:     "config",
	}
	cmd.AddCommand(NewGerritProjectsConfigGetCmd())
	cmd.AddCommand(NewGerritProjectsConfigSetCmd())
	return cmd
}
func NewGerritProjectsConfigGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/config/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Config",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsConfigSetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/config/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Set Config",
		Use:   "set",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsGcCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/gc/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Run GC",
		Use:   "gc",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsBanCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/ban/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Ban Commit",
		Use:   "ban",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsAccessCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Access",
		Use:     "access",
	}
	cmd.AddCommand(NewGerritProjectsAccessListCmd())
	cmd.AddCommand(NewGerritProjectsAccessAddCmd())
	cmd.AddCommand(NewGerritProjectsAccessReviewCmd())
	return cmd
}
func NewGerritProjectsAccessListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/access/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Access Rights for Project",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsAccessAddCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/access/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Add, Update and Delete Access Rights for Project",
		Use:   "add",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsAccessReviewCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/access:review/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Access Rights Change for review.",
		Use:   "review",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsMyProjectCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "MyProject",
		Use:     "MyProject",
	}
	cmd.AddCommand(NewGerritProjectsMyProjectCheckCmd())
	return cmd
}
func NewGerritProjectsMyProjectCheckCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/MyProject/check.access/"
			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Check Access",
		Use:   "check",
	}
	return cmd
}
func NewGerritProjectsBranchesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Branches",
		Use:     "branches",
	}
	cmd.AddCommand(NewGerritProjectsBranchesListCmd())
	cmd.AddCommand(NewGerritProjectsBranchesGetCmd())
	cmd.AddCommand(NewGerritProjectsBranchesCreateCmd())
	cmd.AddCommand(NewGerritProjectsBranchesDeleteCmd())
	cmd.AddCommand(NewGerritProjectsBranchesDelete2Cmd())
	cmd.AddCommand(NewGerritProjectsBranchesFilesCmd())
	cmd.AddCommand(NewGerritProjectsBranchesSuggestReviewersCmd())
	cmd.AddCommand(NewGerritProjectsBranchesMergeableCmd())
	cmd.AddCommand(NewGerritProjectsBranchesReflogCmd())
	return cmd
}
func NewGerritProjectsBranchesListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Branches",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsBranchesGetCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Branch",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsBranchesCreateCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Branch",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsBranchesDeleteCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Branch",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsBranchesDelete2Cmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches:delete/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Branches",
		Use:   "delete-2",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsBranchesFilesCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
		file    string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/files/{file-id}/content/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)
			path = addParamToPath(path, "file-id", cmdFlags.file)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Content",
		Use:   "files",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	cmd.Flags().StringVar(&cmdFlags.file, "file", "", "The file to operate on.")
	cmd.MarkFlagRequired("file")
	return cmd
}
func NewGerritProjectsBranchesSuggestReviewersCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/suggest_reviewers/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Suggest Reviewers",
		Use:   "suggest-reviewers",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsBranchesMergeableCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/mergeable/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Mergeable Information",
		Use:   "mergeable",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsBranchesReflogCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/branches/{branch-id}/reflog/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Reflog",
		Use:   "reflog",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsChangesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Changes",
		Use:     "changes",
	}
	cmd.AddCommand(NewGerritProjectsChangesBranchesCmd())
	return cmd
}
func NewGerritProjectsChangesBranchesCmd() *cobra.Command {
	type flags struct {
		project string
		branch  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/changes/{project-name}/branches/{branch-id}/suggest_reviewers/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "branch-id", cmdFlags.branch)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Suggest Reviewers",
		Use:   "branches",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.branch, "branch", "", "The branch to operate on.")
	cmd.MarkFlagRequired("branch")
	return cmd
}
func NewGerritProjectsChildrenCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Children",
		Use:     "children",
	}
	cmd.AddCommand(NewGerritProjectsChildrenListCmd())
	cmd.AddCommand(NewGerritProjectsChildrenGetCmd())
	return cmd
}
func NewGerritProjectsChildrenListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/children/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Child Projects",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsChildrenGetCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/children/{project-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Child Project",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsTagsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Tags",
		Use:     "tags",
	}
	cmd.AddCommand(NewGerritProjectsTagsCreateCmd())
	cmd.AddCommand(NewGerritProjectsTagsListCmd())
	cmd.AddCommand(NewGerritProjectsTagsGetCmd())
	cmd.AddCommand(NewGerritProjectsTagsDeleteCmd())
	cmd.AddCommand(NewGerritProjectsTagsDelete2Cmd())
	return cmd
}
func NewGerritProjectsTagsCreateCmd() *cobra.Command {
	type flags struct {
		project string
		tag     string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/tags/{tag-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "tag-id", cmdFlags.tag)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Tag",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.tag, "tag", "", "The tag to operate on.")
	cmd.MarkFlagRequired("tag")
	return cmd
}
func NewGerritProjectsTagsListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/tags/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Tags",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsTagsGetCmd() *cobra.Command {
	type flags struct {
		project string
		tag     string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/tags/{tag-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "tag-id", cmdFlags.tag)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Tag",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.tag, "tag", "", "The tag to operate on.")
	cmd.MarkFlagRequired("tag")
	return cmd
}
func NewGerritProjectsTagsDeleteCmd() *cobra.Command {
	type flags struct {
		project string
		tag     string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/tags/{tag-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "tag-id", cmdFlags.tag)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Tag",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.tag, "tag", "", "The tag to operate on.")
	cmd.MarkFlagRequired("tag")
	return cmd
}
func NewGerritProjectsTagsDelete2Cmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/tags:delete/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Tags",
		Use:   "delete-2",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsCommitsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Commits",
		Use:     "commits",
	}
	cmd.AddCommand(NewGerritProjectsCommitsGetCmd())
	cmd.AddCommand(NewGerritProjectsCommitsInCmd())
	cmd.AddCommand(NewGerritProjectsCommitsFilesCmd())
	cmd.AddCommand(NewGerritProjectsCommitsCherrypickCmd())
	return cmd
}
func NewGerritProjectsCommitsGetCmd() *cobra.Command {
	type flags struct {
		project string
		commit  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/commits/{commit-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "commit-id", cmdFlags.commit)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Commit",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.commit, "commit", "", "The commit to operate on.")
	cmd.MarkFlagRequired("commit")
	return cmd
}
func NewGerritProjectsCommitsInCmd() *cobra.Command {
	type flags struct {
		project string
		commit  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/commits/{commit-id}/in/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "commit-id", cmdFlags.commit)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Included In",
		Use:   "in",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.commit, "commit", "", "The commit to operate on.")
	cmd.MarkFlagRequired("commit")
	return cmd
}
func NewGerritProjectsCommitsFilesCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Files",
		Use:     "files",
	}
	cmd.AddCommand(NewGerritProjectsCommitsFilesListCmd())
	cmd.AddCommand(NewGerritProjectsCommitsFilesContentCmd())
	return cmd
}
func NewGerritProjectsCommitsFilesListCmd() *cobra.Command {
	type flags struct {
		project string
		commit  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/commits/{commit-id}/files/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "commit-id", cmdFlags.commit)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Files",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.commit, "commit", "", "The commit to operate on.")
	cmd.MarkFlagRequired("commit")
	return cmd
}
func NewGerritProjectsCommitsFilesContentCmd() *cobra.Command {
	type flags struct {
		project string
		commit  string
		file    string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/commits/{commit-id}/files/{file-id}/content/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "commit-id", cmdFlags.commit)
			path = addParamToPath(path, "file-id", cmdFlags.file)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Content",
		Use:   "content",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.commit, "commit", "", "The commit to operate on.")
	cmd.MarkFlagRequired("commit")
	cmd.Flags().StringVar(&cmdFlags.file, "file", "", "The file to operate on.")
	cmd.MarkFlagRequired("file")
	return cmd
}
func NewGerritProjectsCommitsCherrypickCmd() *cobra.Command {
	type flags struct {
		project string
		commit  string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/commits/{commit-id}/cherrypick/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "commit-id", cmdFlags.commit)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Cherry Pick Commit",
		Use:   "cherrypick",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.commit, "commit", "", "The commit to operate on.")
	cmd.MarkFlagRequired("commit")
	return cmd
}
func NewGerritProjectsDashboardsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Dashboards",
		Use:     "dashboards",
	}
	cmd.AddCommand(NewGerritProjectsDashboardsListCmd())
	cmd.AddCommand(NewGerritProjectsDashboardsGetCmd())
	cmd.AddCommand(NewGerritProjectsDashboardsCreateCmd())
	cmd.AddCommand(NewGerritProjectsDashboardsDeleteCmd())
	return cmd
}
func NewGerritProjectsDashboardsListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/dashboards/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Dashboards",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsDashboardsGetCmd() *cobra.Command {
	type flags struct {
		project   string
		dashboard string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/dashboards/{dashboard-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "dashboard-id", cmdFlags.dashboard)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Dashboard",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.dashboard, "dashboard", "", "The dashboard to operate on.")
	cmd.MarkFlagRequired("dashboard")
	return cmd
}
func NewGerritProjectsDashboardsCreateCmd() *cobra.Command {
	type flags struct {
		project   string
		dashboard string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/dashboards/{dashboard-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "dashboard-id", cmdFlags.dashboard)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Dashboard",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.dashboard, "dashboard", "", "The dashboard to operate on.")
	cmd.MarkFlagRequired("dashboard")
	return cmd
}
func NewGerritProjectsDashboardsDeleteCmd() *cobra.Command {
	type flags struct {
		project   string
		dashboard string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/dashboards/{dashboard-id}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "dashboard-id", cmdFlags.dashboard)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Dashboard",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.dashboard, "dashboard", "", "The dashboard to operate on.")
	cmd.MarkFlagRequired("dashboard")
	return cmd
}
func NewGerritProjectsLabelsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Labels",
		Use:     "labels",
	}
	cmd.AddCommand(NewGerritProjectsLabelsListCmd())
	cmd.AddCommand(NewGerritProjectsLabelsGetCmd())
	cmd.AddCommand(NewGerritProjectsLabelsCreateCmd())
	cmd.AddCommand(NewGerritProjectsLabelsDeleteCmd())
	cmd.AddCommand(NewGerritProjectsLabelsBatchUpdateCmd())
	return cmd
}
func NewGerritProjectsLabelsListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/labels/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Labels",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsLabelsGetCmd() *cobra.Command {
	type flags struct {
		project string
		label   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/labels/{label-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "label-name", cmdFlags.label)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Label",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.label, "label", "", "The label to operate on.")
	cmd.MarkFlagRequired("label")
	return cmd
}
func NewGerritProjectsLabelsCreateCmd() *cobra.Command {
	type flags struct {
		project string
		label   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/labels/{label-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "label-name", cmdFlags.label)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Label",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.label, "label", "", "The label to operate on.")
	cmd.MarkFlagRequired("label")
	return cmd
}
func NewGerritProjectsLabelsDeleteCmd() *cobra.Command {
	type flags struct {
		project string
		label   string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/labels/{label-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "label-name", cmdFlags.label)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Label",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.label, "label", "", "The label to operate on.")
	cmd.MarkFlagRequired("label")
	return cmd
}
func NewGerritProjectsLabelsBatchUpdateCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/labels/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "POST", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Batch Update Labels",
		Use:   "batch-update",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsSubmitRequirementsCmd() *cobra.Command {
	cmd := &cobra.Command{

		Example: "",
		Short:   "Submit Requirements",
		Use:     "submit-requirements",
	}
	cmd.AddCommand(NewGerritProjectsSubmitRequirementsCreateCmd())
	cmd.AddCommand(NewGerritProjectsSubmitRequirementsGetCmd())
	cmd.AddCommand(NewGerritProjectsSubmitRequirementsListCmd())
	cmd.AddCommand(NewGerritProjectsSubmitRequirementsDeleteCmd())
	return cmd
}
func NewGerritProjectsSubmitRequirementsCreateCmd() *cobra.Command {
	type flags struct {
		project           string
		submitrequirement string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/submit_requirements/{submit-requirement-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "submit-requirement-name", cmdFlags.submitrequirement)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "PUT", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Create Submit Requirement",
		Use:   "create",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.submitrequirement, "submitrequirement", "", "The submitrequirement to operate on.")
	cmd.MarkFlagRequired("submitrequirement")
	return cmd
}
func NewGerritProjectsSubmitRequirementsGetCmd() *cobra.Command {
	type flags struct {
		project           string
		submitrequirement string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/submit_requirements/{submit-requirement-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "submit-requirement-name", cmdFlags.submitrequirement)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Get Submit Requirement",
		Use:   "get",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.submitrequirement, "submitrequirement", "", "The submitrequirement to operate on.")
	cmd.MarkFlagRequired("submitrequirement")
	return cmd
}
func NewGerritProjectsSubmitRequirementsListCmd() *cobra.Command {
	type flags struct {
		project string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/submit_requirements/"
			path = addParamToPath(path, "project-name", cmdFlags.project)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "GET", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "List Submit Requirements",
		Use:   "list",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	return cmd
}
func NewGerritProjectsSubmitRequirementsDeleteCmd() *cobra.Command {
	type flags struct {
		project           string
		submitrequirement string
	}
	cmdFlags := flags{}
	cmd := &cobra.Command{

		Example: "",
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project-name}/submit_requirements/{submit-requirement-name}/"
			path = addParamToPath(path, "project-name", cmdFlags.project)
			path = addParamToPath(path, "submit-requirement-name", cmdFlags.submitrequirement)

			client := authenticatedClient(cmd.Context())
			response, err := client.Call(cmd.Context(), "DELETE", path, nil, nil)
			if err != nil {
				return err
			}
			defer response.Body.Close()
			body, err := io.ReadAll(response.Body)
			if err != nil {
				panic(err)
			}
			body = gogerrit.RemoveMagicPrefixLine(body)
			output.NewJSONFromString(string(body), "").Print(cmd.OutOrStdout())
			return nil
		},
		Short: "Delete Submit Requirement",
		Use:   "delete",
	}
	cmd.Flags().StringVar(&cmdFlags.project, "project", "", "The project to operate on.")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&cmdFlags.submitrequirement, "submitrequirement", "", "The submitrequirement to operate on.")
	cmd.MarkFlagRequired("submitrequirement")
	return cmd
}
